### ISSUE TITLE
Use emitter trait

### ISSUE THREAD

**Issue by sagikazarmark** [alexbilbie/Proton#14]
Would be nice to use the `EmitterTrait` from the event package.

**Comment by sagikazarmark** [comment]
Is the `getEventEmitter` remained in the Application for BC?

**Comment by alexbilbie** [comment]
Yes

**Comment by sagikazarmark** [comment]
Could be marked as deprecated and removed in the next major release.

**Comment by alexbilbie** [comment]
What do you think is the best way to do that? E_DEPRECATED notice or is there a docblock or both?

**Comment by sagikazarmark** [comment]
I think a dockblock is enough, as it is probably a notice for us to remove it later. It should be mentioned in the Changelog that it is deprecated and mentioned when it gets removed.
