### ISSUE TITLE
Weird event names

### ISSUE THREAD

**Issue by sagikazarmark** [alexbilbie/Proton#15]
It is weird that some events are in past tense, some aren't:

- RequestReceived
- RequestBefore (could be RequestCreated)
- RequestAfter (could be RequestSent)

**Comment by sagikazarmark** [comment]
@alexbilbie ping :)

**Comment by sagikazarmark** [comment]
Oh, just realised the event names have a suffix `Event`. Is it really necessary? (They are already under the `Events` namespace)

**Comment by GrahamCampbell** [comment]
I like suffixes. :)

**Comment by alexbilbie** [comment]
I'm thinking it's best to remove the library specific event classes and just fire normal `League\Event\Event`s.

i.e. replace this:

```php
$this->emit(
   (new Events\ResponseBeforeEvent($request, $response))
);
```

with:

```php
$this->emit('response.before', $response);
```

**Comment by sagikazarmark** [comment]
There is not too much domain logic here, so that could work as well. However the past tense thing is still valid IMO:

* request.recieved
* response.created
* response.sent

**Comment by alexbilbie** [comment]
All three of those work for me.

Want to create a PR for me? :smile:

**Comment by sagikazarmark** [comment]
Sure, I'm on it.

**Comment by alexbilbie** [comment]
Resolved
