### ISSUE TITLE
[Insight] Projects must not depend on dependencies with known security issues

### ISSUE THREAD

**Issue by alexbilbie** [alexbilbie/Proton#27]
> The checker detected 1 security issues in package symfony/http-kernel installed in version 2.6.5.0 1) Esi Code Injection.

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/d37b757f-40bf-46a9-8f64-fa001c7ff129/analyses/75)_

**Comment by GrahamCampbell** [comment]
This fix looks incorrect to me.

**Comment by GrahamCampbell** [comment]
SYmfony less than 2.5.11 was also affected by the bug.

**Comment by GrahamCampbell** [comment]
Here's a fix: https://github.com/alexbilbie/Proton/pull/33.

**Comment by GrahamCampbell** [comment]
Also, this PR broke all the indention in the composer.json file.
